-- MathHub Supabase database setup
-- Run this in Supabase SQL Editor after creating your project.
--
-- This schema stores user profiles, completed lessons and quiz scores.
-- Row Level Security ensures users can only access their own records.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  created_at timestamptz not null default now()
);

create table if not exists public.lesson_progress (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  lesson_key text not null,
  completed_at timestamptz not null default now(),
  unique(user_id, lesson_key)
);

create table if not exists public.quiz_scores (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  subject text not null,
  score integer not null,
  total integer not null,
  percentage integer not null,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.lesson_progress enable row level security;
alter table public.quiz_scores enable row level security;

drop policy if exists "Users can view own profile" on public.profiles;
drop policy if exists "Users can update own profile" on public.profiles;
drop policy if exists "Users can insert own profile" on public.profiles;

create policy "Users can view own profile"
on public.profiles for select
to authenticated
using (auth.uid() = id);

create policy "Users can update own profile"
on public.profiles for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

create policy "Users can insert own profile"
on public.profiles for insert
to authenticated
with check (auth.uid() = id);

drop policy if exists "Users can view own lesson progress" on public.lesson_progress;
drop policy if exists "Users can insert own lesson progress" on public.lesson_progress;
drop policy if exists "Users can update own lesson progress" on public.lesson_progress;
drop policy if exists "Users can delete own lesson progress" on public.lesson_progress;

create policy "Users can view own lesson progress"
on public.lesson_progress for select
to authenticated
using (auth.uid() = user_id);

create policy "Users can insert own lesson progress"
on public.lesson_progress for insert
to authenticated
with check (auth.uid() = user_id);

create policy "Users can update own lesson progress"
on public.lesson_progress for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Users can delete own lesson progress"
on public.lesson_progress for delete
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can view own quiz scores" on public.quiz_scores;
drop policy if exists "Users can insert own quiz scores" on public.quiz_scores;

create policy "Users can view own quiz scores"
on public.quiz_scores for select
to authenticated
using (auth.uid() = user_id);

create policy "Users can insert own quiz scores"
on public.quiz_scores for insert
to authenticated
with check (auth.uid() = user_id);

-- Create a profile automatically when a user signs up.
create or replace function public.handle_new_mathhub_user()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
begin
  insert into public.profiles (id, full_name)
  values (
    new.id,
    new.raw_user_meta_data ->> 'full_name'
  )
  on conflict (id) do update
  set full_name = excluded.full_name;

  return new;
end;
$$;

drop trigger if exists on_mathhub_user_created on auth.users;

create trigger on_mathhub_user_created
after insert on auth.users
for each row
execute procedure public.handle_new_mathhub_user();
