// ===============================
// MATHHUB CALCULUS LESSONS
// ===============================

const calculusTopics = ["Introduction to Calculus","Functions and Calculus","Domain and Range","Limits","Evaluating Limits","Limit Laws","One-Sided Limits","Limits at Infinity","Infinite Limits","Continuity","Continuous Functions","Discontinuities","Average Rate of Change","Instantaneous Rate of Change","The Derivative","Derivative Notation","Basic Differentiation Rules","Power Rule","Constant Rule","Sum and Difference Rules","Product Rule","Quotient Rule","Chain Rule","Derivatives of Polynomials","Derivatives of Rational Functions","Derivatives of Exponential Functions","Derivatives of Logarithmic Functions","Derivatives of Sine","Derivatives of Cosine","Derivatives of Tangent","Derivatives of Trigonometric Functions","Implicit Differentiation","Higher-Order Derivatives","Second Derivative","Related Rates","Linear Approximation","Differentials","Critical Points","Increasing and Decreasing Functions","First Derivative Test","Local Maximum and Minimum","Absolute Maximum and Minimum","Concavity","Inflection Points","Second Derivative Test","Curve Sketching","Optimization","Applications of Derivatives","Motion Along a Line","Velocity and Acceleration","Introduction to Integration","Antiderivatives","Indefinite Integrals","Constant of Integration","Basic Integration Rules","Power Rule for Integration","Sum and Difference Integration","Definite Integrals","Riemann Sums","The Fundamental Theorem of Calculus","Area Under a Curve","Area Between Curves","Average Value of a Function","Substitution Method","Integration by Substitution","Integration of Exponential Functions","Integration of Logarithmic Functions","Integration of Trigonometric Functions","Integration by Parts","Partial Fractions","Improper Integrals","Numerical Integration","Trapezoidal Rule","Midpoint Rule","Simpson's Rule","Volumes by Slicing","Volumes by Disks","Volumes by Washers","Volumes by Cylindrical Shells","Arc Length","Parametric Equations","Parametric Derivatives","Polar Coordinates","Polar Area","Sequences","Series","Arithmetic Sequences","Geometric Sequences","Infinite Geometric Series","Convergence of Series","Power Series","Taylor Series","Maclaurin Series","Taylor Polynomial","Applications of Taylor Series","Differential Equations Introduction","Slope Fields","Separable Differential Equations","Growth and Decay Models","Calculus Review"];

const calculusSpecificContent = {"Introduction to Calculus":"Calculus studies change and accumulation. Its two main ideas are differentiation and integration.","Limits":"A limit describes the value a function approaches as the input approaches a particular value.","Continuity":"A function is continuous at a point when its value agrees with the value it approaches there.","Average Rate of Change":"The average rate of change of f(x) from a to b is (f(b)-f(a))/(b-a).","The Derivative":"The derivative measures instantaneous rate of change and is the slope of a tangent line.","Power Rule":"For x^n, the derivative is nx^(n-1).","Product Rule":"For u and v, (uv)' = u'v + uv'.","Quotient Rule":"For u/v, the derivative is (u'v-uv')/v².","Chain Rule":"For y=f(g(x)), y'=f'(g(x))g'(x).","Implicit Differentiation":"Differentiate both sides with respect to x when y is not isolated.","Critical Points":"Critical points occur where f'(x)=0 or where f'(x) does not exist, subject to the domain.","Optimization":"Optimization uses derivatives to find maximum and minimum values.","The Fundamental Theorem of Calculus":"The Fundamental Theorem connects differentiation and integration.","Area Under a Curve":"A definite integral can represent signed area between a graph and the x-axis.","Substitution Method":"u-substitution replaces a complicated inner expression with a new variable.","Integration by Parts":"Integration by parts uses ∫u dv = uv - ∫v du.","Volumes by Disks":"The disk method uses circular cross-sections to calculate volume.","Taylor Series":"A Taylor series represents a function as an infinite power series around a chosen center.","Differential Equations Introduction":"A differential equation contains an unknown function and one or more derivatives."};

const calculusDescriptions = {"Limits":"Understand what a function approaches as the input approaches a value.","The Derivative":"Learn how derivatives measure instantaneous change and slope.","Power Rule":"Differentiate powers quickly using the power rule.","Chain Rule":"Differentiate composite functions using the chain rule.","Optimization":"Use derivatives to solve maximum and minimum problems.","The Fundamental Theorem of Calculus":"Connect differentiation and integration.","Area Under a Curve":"Use definite integrals to find signed area.","Taylor Series":"Represent functions using power series.","Differential Equations Introduction":"Understand equations involving unknown functions and derivatives."};

const calculusLessons = calculusTopics.map((title, index) => ({
  id: index + 1,
  title,
  description: calculusDescriptions[title] || `Learn the fundamental ideas and techniques of ${title.toLowerCase()} in calculus.`,
  content: calculusSpecificContent[title]
    ? `<p>${calculusSpecificContent[title]}</p>`
    : `<p>This lesson introduces <strong>${title}</strong> and explains how it is used in calculus.</p><h4>Key idea</h4><p>Study the definition, identify the relevant formula or rule, and apply it carefully to examples.</p><h4>Practice tip</h4><p>Work through simple examples first, then increase the difficulty as you become comfortable with the method.</p>`,
  practice: [
    { question: "What is the derivative of x²?", answer: 2, explanation: "By the power rule, d/dx(x²) = 2x; at x = 1 the value is 2." },
    { question: "What is the integral of 2x?", answer: 0, explanation: "∫2x dx = x² + C." },
    { question: "What is the limit of x + 3 as x approaches 2?", answer: 5, explanation: "Substitute x = 2: 2 + 3 = 5." },
    { question: "What is the derivative of a constant?", answer: 0, explanation: "The derivative of any constant is zero." },
    { question: "What is the integral of 1 with respect to x?", answer: 0, explanation: "∫1 dx = x + C." }
  ]
}));