const statisticsTopics = [
  "Introduction to Statistics",
  "Population and Sample",
  "Types of Data",
  "Qualitative Data",
  "Quantitative Data",
  "Discrete Data",
  "Continuous Data",
  "Primary Data",
  "Secondary Data",
  "Variables",
  "Frequency",
  "Frequency Tables",
  "Tally Charts",
  "Grouped Frequency Tables",
  "Class Intervals",
  "Class Limits",
  "Class Boundaries",
  "Class Width",
  "Midpoints",
  "Cumulative Frequency",
  "Mean of Ungrouped Data",
  "Mean from a Frequency Table",
  "Mean of Grouped Data",
  "Weighted Mean",
  "Median",
  "Median for Even Data",
  "Mode",
  "Range",
  "Quartiles",
  "Percentiles",
  "Interquartile Range",
  "Five-Number Summary",
  "Box-and-Whisker Plots",
  "Outliers",
  "Mean and Outliers",
  "Median and Outliers",
  "Measures of Central Tendency",
  "Measures of Dispersion",
  "Variance",
  "Population Variance",
  "Sample Variance",
  "Standard Deviation",
  "Population Standard Deviation",
  "Sample Standard Deviation",
  "Coefficient of Variation",
  "Data Distribution",
  "Symmetric Distribution",
  "Skewed Distribution",
  "Positive Skew",
  "Negative Skew",
  "Frequency Polygons",
  "Histograms",
  "Bar Charts",
  "Pie Charts",
  "Line Graphs",
  "Stem-and-Leaf Plots",
  "Scatter Plots",
  "Correlation",
  "Positive Correlation",
  "Negative Correlation",
  "Zero Correlation",
  "Correlation Coefficient",
  "Strong and Weak Correlation",
  "Correlation Is Not Causation",
  "Simple Probability",
  "Probability Scale",
  "Sample Space",
  "Events",
  "Simple Events",
  "Compound Events",
  "Complementary Events",
  "Mutually Exclusive Events",
  "Independent Events",
  "Dependent Events",
  "Addition Rule",
  "Multiplication Rule",
  "Conditional Probability",
  "Tree Diagrams",
  "Two-Way Tables",
  "Expected Value",
  "Binomial Experiments",
  "Binomial Probability",
  "Normal Distribution",
  "Standard Normal Distribution",
  "Z-Scores",
  "Empirical Rule",
  "Sampling Methods",
  "Simple Random Sampling",
  "Systematic Sampling",
  "Stratified Sampling",
  "Cluster Sampling",
  "Sampling Bias",
  "Response Bias",
  "Experimental Design",
  "Observational Studies",
  "Randomized Experiments",
  "Control Groups",
  "Statistical Inference",
  "Confidence Intervals",
  "Margin of Error",
  "Hypothesis Testing",
  "Null and Alternative Hypotheses",
  "P-Values",
  "Significance Level",
  "Type I and Type II Errors",
  "Regression",
  "Linear Regression",
  "Least Squares",
  "Residuals",
  "Coefficient of Determination"
];

const statisticsLessons = statisticsTopics.map((title, index) => {
  const n = index + 1;

  return {
    id: n,
    title,
    description: "Learn " + title.toLowerCase() + " through simple explanations and practice.",
    content: `
      <h3>${title}</h3>
      <p>${getStatisticsExplanation(title)}</p>
      <h3>Key Idea</h3>
      <p>Understand the definition, identify the relevant statistical concept, and use the practice questions to check your understanding.</p>
    `,
    practice: [
      { question: "How many values are in the basic practice set?", answer: 5 },
      { question: "If a value occurs 3 times, what is its frequency?", answer: 3 },
      { question: "What is 10% of 50?", answer: 5 },
      { question: "What is 25% of 20?", answer: 5 },
      { question: "What is the difference between 12 and 7?", answer: 5 }
    ]
  };
});

function getStatisticsExplanation(title) {
  const explanations = {
    "Introduction to Statistics": "Statistics is the study of collecting, organizing, analyzing and interpreting data.",
    "Population and Sample": "A population contains all members of interest, while a sample is a subset selected for study.",
    "Types of Data": "Data may be qualitative or quantitative; quantitative data are numerical.",
    "Mean of Ungrouped Data": "Mean = sum of observations divided by the number of observations.",
    "Mean from a Frequency Table": "For a frequency table, mean = sum of fx divided by sum of f.",
    "Median": "The median is the central observation after arranging data in order.",
    "Mode": "The mode is the value or category occurring most often.",
    "Range": "Range = maximum value minus minimum value.",
    "Interquartile Range": "IQR = Q3 minus Q1.",
    "Standard Deviation": "Standard deviation is the square root of variance.",
    "Coefficient of Variation": "Coefficient of variation = standard deviation divided by mean, multiplied by 100%.",
    "Histograms": "A histogram uses adjacent bars to show frequencies across class intervals.",
    "Bar Charts": "A bar chart compares categories using separated rectangular bars.",
    "Pie Charts": "A pie chart uses sectors whose angles represent category proportions.",
    "Scatter Plots": "A scatter plot places paired observations on coordinate axes.",
    "Correlation Coefficient": "For a standard Pearson correlation, r ranges from -1 to +1.",
    "Simple Probability": "For equally likely outcomes, probability = favorable outcomes divided by total outcomes.",
    "Probability Scale": "Probability ranges from 0 for impossible to 1 for certain.",
    "Complementary Events": "P(not A) = 1 - P(A).",
    "Independent Events": "For independent events, P(A and B) = P(A)P(B).",
    "Addition Rule": "P(A or B) = P(A) + P(B) - P(A and B).",
    "Multiplication Rule": "For suitable independent events, P(A and B) = P(A)P(B).",
    "Conditional Probability": "P(A|B) = P(A and B) / P(B), when P(B) is nonzero.",
    "Expected Value": "Expected value is the sum of each outcome multiplied by its probability.",
    "Z-Scores": "z = (x - mean) / standard deviation.",
    "Empirical Rule": "For a normal distribution, about 68%, 95% and 99.7% lie within 1, 2 and 3 standard deviations.",
    "Sampling Bias": "Sampling bias occurs when the selection process systematically misrepresents the population.",
    "Statistical Inference": "Statistical inference uses sample information to draw conclusions about a population.",
    "Confidence Intervals": "A confidence interval gives a range of plausible values for a population parameter under stated assumptions.",
    "Hypothesis Testing": "Hypothesis testing compares sample evidence with a stated null hypothesis.",
    "P-Values": "A p-value measures how unusual the observed data would be if the null hypothesis were true.",
    "Linear Regression": "A simple linear regression model has the form y = a + bx.",
    "Residuals": "A residual is observed value minus predicted value.",
    "Coefficient of Determination": "R² describes the proportion of variation in a response explained by a fitted regression model."
  };

  return explanations[title] || "This lesson introduces the main ideas, terminology and applications of " + title.toLowerCase() + " in statistics.";
}
